export interface Product {
  slug: string;
  name: string;
  category: 'cake' | 'pastry' | 'dessert' | 'bread' | 'special';
  shortDescription: string;
  description: string;
  ingredients: string[];
  craftNotes?: string;
  pairingSuggestions?: string[];
  allergens: string[];
  heroImage?: string;
  gallery?: string[];
}

export const products: Product[] = [
  {
    slug: 'cikolatali-mousse-kek',
    name: 'Çikolatalı Mousse Kek',
    category: 'cake',
    shortDescription: 'Belçika çikolatası ile hazırlanmış, hafif ve yoğun lezzetli mousse kek.',
    description: 'En kaliteli Belçika çikolatasından yapılan bu mousse kek, her dilimde mükemmel bir doku ve lezzet sunar. Özel tarifimizle hazırlanan bu kek, çikolata severler için unutulmaz bir deneyim.',
    ingredients: [
      'Belçika bitter çikolata %70',
      'Taze yumurta',
      'Krem şanti',
      'Vanilya özü',
      'Tereyağı',
      'Un',
    ],
    craftNotes: 'Her katman ayrı ayrı hazırlanır ve 24 saat soğutulur. Çikolata temperleme tekniği ile mükemmel parlaklık sağlanır.',
    pairingSuggestions: ['Espresso', 'Earl Grey çay', 'Kırmızı şarap'],
    allergens: ['Yumurta', 'Süt', 'Gluten', 'Soya'],
  },
  {
    slug: 'frambuazli-cheesecake',
    name: 'Frambuazlı Cheesecake',
    category: 'dessert',
    shortDescription: 'Krem peynir ve taze frambuazın mükemmel uyumu.',
    description: 'New York tarzı cheesecake\'imiz, taze frambuaz sosu ile zenginleştirilmiş. Her lokmada kremsi doku ve meyvenin doğal tatlılığı.',
    ingredients: [
      'Krem peynir',
      'Taze frambuaz',
      'Graham cracker',
      'Krem şanti',
      'Limon',
      'Vanilya',
    ],
    craftNotes: 'Geleneksel su banyosu yöntemi ile pişirilir, yavaş soğutma ile çatlaması önlenir.',
    pairingSuggestions: ['Beyaz çay', 'Prosecco'],
    allergens: ['Yumurta', 'Süt', 'Gluten'],
  },
  {
    slug: 'croissant',
    name: 'Tereyağlı Croissant',
    category: 'pastry',
    shortDescription: 'Fransız usulü, kat kat açılmış mükemmel croissant.',
    description: 'Geleneksel Fransız tekniği ile hazırlanan croissant\'ımız, 72 saatlik bir süreçten geçer. Her katman ayrı ayrı açılır ve mükemmel bir doku elde edilir.',
    ingredients: [
      'Fransız tereyağı',
      'Organik un',
      'Tuz',
      'Şeker',
      'Maya',
    ],
    craftNotes: 'Laminasyon işlemi 3 gün sürer. Her katmanın mükemmel açılması için özel sıcaklık kontrolü uygulanır.',
    pairingSuggestions: ['Kahve', 'Portakal suyu'],
    allergens: ['Gluten', 'Süt', 'Yumurta'],
  },
  {
    slug: 'tiramisu',
    name: 'Tiramisu',
    category: 'dessert',
    shortDescription: 'İtalyan klasik, espresso ve mascarpone\'un zarif dansı.',
    description: 'Geleneksel İtalyan tarifi ile hazırlanan tiramisu\'muz, özel espresso ve mascarpone ile zenginleştirilmiş. Her katman ayrı bir hikaye anlatır.',
    ingredients: [
      'Mascarpone',
      'Espresso',
      'Savoiardi bisküvi',
      'Kakao',
      'Yumurta',
      'Marsala şarabı',
    ],
    craftNotes: '24 saat dinlendirilir. Her katman ayrı ayrı hazırlanır ve mükemmel bir doku için özel teknik kullanılır.',
    pairingSuggestions: ['Espresso', 'Amaretto'],
    allergens: ['Yumurta', 'Süt', 'Gluten', 'Alkol'],
  },
  {
    slug: 'ekmek',
    name: 'Ekşi Mayalı Ekmek',
    category: 'bread',
    shortDescription: 'Geleneksel ekşi maya ile 48 saatlik fermantasyon.',
    description: 'Atalardan gelen ekşi maya kültürümüz ile hazırlanan ekmek, 48 saatlik doğal fermantasyon sürecinden geçer. Her dilimde derin bir lezzet ve mükemmel bir doku.',
    ingredients: [
      'Ekşi maya',
      'Organik un',
      'Su',
      'Tuz',
    ],
    craftNotes: 'Geleneksel ekşi maya kültürü 20 yıldır korunuyor. Her ekmek 48 saatlik doğal fermantasyon sürecinden geçer.',
    pairingSuggestions: ['Zeytinyağı', 'Peynir', 'Bal'],
    allergens: ['Gluten'],
  },
  {
    slug: 'macaron-karisimi',
    name: 'Macaron Karışımı',
    category: 'pastry',
    shortDescription: 'Fransız usulü, 12 farklı lezzet.',
    description: 'Geleneksel Fransız tekniği ile hazırlanan macaron\'larımız, 12 farklı lezzet seçeneği sunar. Her biri mükemmel bir doku ve dengeli bir tat sunar.',
    ingredients: [
      'Badem unu',
      'Toz şeker',
      'Yumurta akı',
      'Gıda boyası',
      'Çeşitli dolgular',
    ],
    craftNotes: 'Her macaron elle şekillendirilir. Mükemmel "feet" oluşumu için özel sıcaklık ve nem kontrolü uygulanır.',
    pairingSuggestions: ['Champagne', 'Earl Grey çay'],
    allergens: ['Yumurta', 'Badem', 'Süt'],
  },
  {
    slug: 'profiterol',
    name: 'Profiterol',
    category: 'dessert',
    shortDescription: 'Krem şanti dolu, çikolata soslu klasik.',
    description: 'Hafif choux hamurundan yapılan profiterol\'lerimiz, krem şanti ile doldurulur ve sıcak çikolata sosu ile servis edilir.',
    ingredients: [
      'Choux hamuru',
      'Krem şanti',
      'Bitter çikolata',
      'Tereyağı',
      'Yumurta',
    ],
    craftNotes: 'Choux hamuru özel teknik ile pişirilir. İç dolgu servis anında eklenir, tazeliği korunur.',
    pairingSuggestions: ['Espresso', 'Sütlü kahve'],
    allergens: ['Yumurta', 'Süt', 'Gluten'],
  },
  {
    slug: 'eclair',
    name: 'Éclair',
    category: 'pastry',
    shortDescription: 'Uzun, zarif, krem dolu Fransız klasiği.',
    description: 'Geleneksel Fransız éclair\'imiz, vanilyalı krem ile doldurulur ve fondant ile kaplanır. Her ısırıkta mükemmel bir doku.',
    ingredients: [
      'Choux hamuru',
      'Vanilyalı krem',
      'Fondant',
      'Yumurta',
      'Tereyağı',
    ],
    craftNotes: 'Uzun şekil elle şekillendirilir. Mükemmel dolgu için özel enjektör kullanılır.',
    pairingSuggestions: ['Cappuccino', 'Siyah çay'],
    allergens: ['Yumurta', 'Süt', 'Gluten'],
  },
  {
    slug: 'opera-kek',
    name: 'Opera Kek',
    category: 'cake',
    shortDescription: 'Kahve ve çikolatanın zarif uyumu.',
    description: 'Geleneksel Fransız Opera keki, kahve ve çikolatanın mükemmel uyumunu sunar. Her katman ayrı bir lezzet hikayesi anlatır.',
    ingredients: [
      'Badem unu',
      'Espresso',
      'Bitter çikolata',
      'Krema',
      'Kakao',
    ],
    craftNotes: '7 katmanlı yapı, her biri ayrı ayrı hazırlanır. Mükemmel denge için özel teknik uygulanır.',
    pairingSuggestions: ['Espresso', 'Cognac'],
    allergens: ['Yumurta', 'Badem', 'Süt', 'Gluten'],
  },
  {
    slug: 'sufle',
    name: 'Çikolatalı Sufle',
    category: 'dessert',
    shortDescription: 'Sıcak, akışkan, mükemmel zamanlama.',
    description: 'Sipariş üzerine hazırlanan sufle\'miz, mükemmel zamanlama ile servis edilir. Her kaşıkta sıcak çikolata akışı.',
    ingredients: [
      'Bitter çikolata',
      'Yumurta',
      'Şeker',
      'Tereyağı',
      'Un',
    ],
    craftNotes: 'Sipariş anında hazırlanır. Mükemmel yükselme için özel fırın tekniği kullanılır.',
    pairingSuggestions: ['Vanilyalı dondurma', 'Espresso'],
    allergens: ['Yumurta', 'Süt', 'Gluten'],
  },
  {
    slug: 'tart',
    name: 'Meyveli Tart',
    category: 'pastry',
    shortDescription: 'Taze mevsim meyveleri ile zenginleştirilmiş.',
    description: 'Kırılgan tart hamuru, krem patisserie ve taze mevsim meyveleri ile hazırlanan bu tart, her mevsim farklı bir lezzet sunar.',
    ingredients: [
      'Tart hamuru',
      'Krem patisserie',
      'Mevsim meyveleri',
      'Agar agar',
      'Şeker',
    ],
    craftNotes: 'Hamur 24 saat dinlendirilir. Meyveler günlük olarak seçilir ve elle yerleştirilir.',
    pairingSuggestions: ['Beyaz şarap', 'Yeşil çay'],
    allergens: ['Gluten', 'Yumurta', 'Süt'],
  },
  {
    slug: 'ozel-karisim',
    name: 'Özel Karışım Kek',
    category: 'special',
    shortDescription: 'Şef\'in özel tarifi, sınırlı üretim.',
    description: 'Şefimizin özel tarifi ile hazırlanan bu kek, sınırlı sayıda üretilir. Her ay farklı bir lezzet kombinasyonu sunar.',
    ingredients: [
      'Özel karışım',
      'Seçilmiş çikolata',
      'Taze meyveler',
      'Özel baharatlar',
    ],
    craftNotes: 'Her ay yenilenen tarif. Sınırlı üretim, mükemmel kalite.',
    pairingSuggestions: ['Şef\'in önerisi'],
    allergens: ['Yumurta', 'Süt', 'Gluten'],
  },
];

